import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProviderStore from "@/store/ProviderStore";
import { Toaster } from "react-hot-toast";
import MainLayout from "@/components/MainLayout ";
import TanstackProvider from "@/hooks/TanstackProvider";
import Header from "@/components/Header";
import MainWrapper from "@/components/MainWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />

        <ProviderStore>
          <TanstackProvider>
            <MainWrapper>
              <MainLayout>
                <Header />
                {children}
              </MainLayout>
            </MainWrapper>
          </TanstackProvider>
        </ProviderStore>
      </body>
    </html>
  );
}
